require 'json'
require 'redis'
require 'mongo'

desc 'Process some incoming words from Redis'
task 'process' do
	redis_credentials = JSON.parse(ENV['VCAP_SERVICES'])["user-provided"].select { |service| service["name"] == "redis" }.first["credentials"]
  redis = Redis.new(:host => redis_credentials["hostname"], :port => redis_credentials["port"])

	mongo_credentials = JSON.parse(ENV['VCAP_SERVICES'])["user-provided"].select { |service| service["name"] == "mongo" }.first["credentials"]
  mongo = Mongo::MongoClient.new(mongo_credentials["hostname"], mongo_credentials["port"]).db('worddb')['words']

  loop do 
		while word = redis.lpop('words') do
			#process
			puts 'Found a word! Processing: ' + word
			doc = mongo.find("word" => word).to_a.first
			unless doc = mongo.find("word" => word).to_a.first then
				#insert
				mongo.insert({"word" => word, "count" => 1})
			else
				#update
				mongo.update({"_id" => doc["_id"]}, {"$set" => {"count" => doc["count"] + 1}})
			end
		end
		sleep 1
  end
end